# Generated by Django 6.1.2 on 2026-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoperatortransaction',
            name='sequence_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
