# Generated by Django 5.1.1 on 2026-10-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_emial_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='id_est_ch',
        ),
        migrations.RemoveField(
            model_name='checkinout',
            name='id_p',
        ),
        migrations.RemoveField(
            model_name='checkinout',
            name='id_reserva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_reg',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_h',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='id_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='id_h',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='id_th',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_h',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_reserva',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id_tp',
        ),
        migrations.DeleteModel(
            name='EstadoCheckInOut',
        ),
        migrations.DeleteModel(
            name='CheckInOut',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='EstadoReserva',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='TipoPersonal',
        ),
    ]
